app/page.tsx, biome.json, package-lock.json, package.json
Biome 띄어쓰기 추가 설정 및 day-picker 버전 다운그레이드
위 내용과 같습니다.
=> Biome 추가 설정 및 의존성 수정

app/globals.css, components/common/InputCalendar.tsx, components/ui/calendar.tsx, package-lock.json, package.json
- shadcn 버전 업데이트에 따른 `react-day-picker` 의존성 충돌 이슈 해결
Closes #34 
- react-datepicker 교체 후 커스텀 스타일 반영했습니다.
=> 공통 컴포넌트 - Calendar 오류 수정

app/globals.css, app/page.tsx, components/common/ListCard.tsx, components/common/SubHeader.tsx, components/ui/badge.tsx, components/ui/button.tsx, components/ui/tabs.tsx, package-lock.json, package.json, tailwind.config.ts
- badge, listCard 디자인 변경에 따른 스타일 변경
- 공통 컴포넌트 추가 제작
Closes #8 
- badge, listCard 스타일 수정
- 공통 컴포넌트 tabs 추가 - shadcn 디자인과 맞지 않아 스타일 수정
- 2뎁스 헤더용 SubHeader 컴포넌트 추가
SubHeader 는
- SubHeaderProps 로 title, icon, desc 등 받아서 적용되도록 작업
- 채팅에 쓰이는 버전은 별도 개발이 되어야 할 것 같아서 추가 x
=> 공통 컴포넌트 - 스타일 수정 및 tabs, subHeader 추가

app/api/chat/[chatId]/shares/complete/route.ts, app/api/chat/[chatId]/shares/confirm/route.ts, app/api/chat/[chatId]/shares/route.ts, app/api/chat/[chatId]/together/complete/route.ts, app/api/chat/[chatId]/together/route.ts, app/api/group-buys/[groupBuyId]/route.ts, app/api/shares/[shareId]/route.ts
Closes #102 
- api/[slug] 하위 route 파일에서 인자값 타입에러 발생하여 전체 수정
- promise 로 넘기고 await 으로 값 받도록 + 코드 공통화
- 자세한 코드 내용은 issue 에 작성해 놓았습니다.
- 같은 파일 수정하여 충돌나면 이 버전으로 맞춰주세요!
=> dynamic-api 관련 promise 추가, 코드 공통화

app/api/chat/[chatId]/shares/complete/route.ts, app/api/chat/[chatId]/shares/confirm/route.ts, app/api/chat/[chatId]/shares/route.ts, app/api/chat/[chatId]/together/complete/route.ts, app/api/chat/[chatId]/together/route.ts, app/api/group-buys/[groupBuyId]/route.ts, app/api/shares/[shareId]/route.ts
#102 
- 수정하다가 값을 잘못 받아서, 재수정 합니다. 쒀리
=> fix: route 받는 값 에러 수정

app/api/group-buys/[groupBuyId]/edit/route.ts, app/api/group-buys/[groupBuyId]/route.ts, app/group-buy/[groupbuyId]/edit/hooks/useGroupBuyFormDetail.ts, app/group-buy/[groupbuyId]/edit/page.tsx, application/usecases/group-buy/GetGroupBuyFormDetailUsecase.ts, application/usecases/group-buy/UpdateGroupBuyUsecase.ts, application/usecases/group-buy/dto/GetGroupBuyFormDetailDto.ts, application/usecases/group-buy/dto/UpdateGroupBuyDto.ts, domain/repositories/group-buy/GroupBuyImageRepository.ts, domain/repositories/group-buy/GroupBuyRepository.ts, infra/repositories/prisma/group-buy/PrismaGroupBuyImageRepository.ts, infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
closes #93
- 같이 장보기 게시글 수정 기능 구현
- 작성자만 수정 가능
- 작성자 이외 회원이 접근할 경우
- <img src='https://github.com/user-attachments/assets/1f2c47b8-e494-4025-bb64-2f62e102a803' width='500px' />
- 없는 장보기 id로 접근한 경우
- <img width="500" alt="image" src="https://github.com/user-attachments/assets/b3d1720d-f93d-4a0c-8ca0-19c69b3c2350" />
=> feat : 같이 장보기 수정 페이지 구현

app/api/group-buys/route.ts, application/usecases/group-buy/CreateGroupBuyUsecase.ts, domain/repositories/chat/GroupBuyChatParticipantRepository.ts, domain/repositories/chat/GroupBuyChatRepository.ts, infra/repositories/prisma/chat/PrismaGroupBuyChatParticipantRepository.ts, infra/repositories/prisma/chat/PrismaGroupBuyChatRepository.ts
closes #114
- 같이 장보기 등록 시 채팅방 생성
- GroupBuyChat 데이터 추가
- GroupBuyChatParticipant에 주최자 데이터 추가
=> 같이 장보기 등록 시 채팅방 생성 로직 추가

app/auth/onboarding/page.tsx, app/auth/post-login/page.tsx, lib/authOptions.ts, middleware.ts
closes #119 
- 로그인한 유저가 `/onboarding`, `post-login` 페이지에 접근할 수 없도록 제한
- 회원가입(주소 입력) 도중 페이지 이탈한 경우
- 회원만 사용가능한 페이지 접근 시 `/onboarding`으로 리다이렉트
=> 인증 관련 예외 처리

app/api/share-items/route.ts, app/group-buy/[groupBuyId]/edit/page.tsx, app/register/group-buy/page.tsx, app/register/share/page.tsx, app/review/new/hooks/useValidateReviewWritable.ts, app/review/new/page.tsx, app/share/[shareId]/edit/page.tsx, application/usecases/group-buy/CreateGroupBuyUsecase.ts, application/usecases/share/GetShareItemsUsecase.ts, components/common/KakaoMap.tsx, components/common/register/FormButton.tsx, domain/repositories/share/ShareItemRepository.ts, domain/repositories/share/ShareRepository.ts, infra/repositories/prisma/chat/PrismaGroupBuyChatParticipantRepository.ts, infra/repositories/prisma/chat/PrismaGroupBuyChatRepository.ts, infra/repositories/prisma/share/PrismaShareItemRepository.ts, infra/repositories/prisma/share/PrismaShareRepository.ts
closes #125
- 나눔 항목 필터링
- 사용자가 최근 24시간 이내 등록한 `shareItem`은 다시 선택할 수 없도록 필터링
- 해당 항목이 없을 경우 셀렉트 박스 비활성화 및 안내 문구 표시
- 폼 제출 중 버튼 비활성화 처리
=> 최근 등록한 나눔 항목 등록 제한

app/map/components/MapView.tsx
=> maplibre 타입 명시화 및 오류 해결

app/chat/components/ChatMessage.tsx, app/chat/components/ChatMessageList.tsx, app/chat/components/ChatRoom.tsx, infra/repositories/prisma/PrismaChatListRepository.ts, prisma/schema.prisma
- 후기에 slug를 사용해서 그렇게 사용할 수 있도록 후기 채팅 링크도 수정했습니다.
=> 후기 관련해서 props 수정

app/chat/components/ChatRoom.tsx, app/chat/components/ShareInfo.tsx, app/chat/components/TogetherInfo.tsx, application/usecases/chat/dto/ChatDetailDto.ts, domain/repositories/chat/ChatMessageListRepository.ts, infra/repositories/prisma/PrismaChatMessageListRepository.ts
- 이미지를 배열로 불러오는데, 그냥 imageUrl로 해서 안나오던 오류 수정했습니다.
=> 나눔 헤더에서 이미지 제대로 못불러오던 오류 수정

app/chat/components/ChatList.tsx, app/chat/components/TogetherInfo.tsx, infra/repositories/prisma/share-box/PrismaShareListRepository.ts
- 채팅방에서 사진을 제대로 가져오지 못하는 오류를 수정했습니다.
- 나눔함에서 삭제된 항목을 가져오지 않도록 수정했습니다.
=> 여러 에러 수정(채팅, 나눔함 관련)

app/chat/components/ChatList.tsx, app/chat/components/Tab.tsx, app/chat/page.tsx, application/usecases/chat/dto/ChatListItemDto.ts, infra/repositories/prisma/PrismaChatListRepository.ts, package-lock.json
- 나눔 채팅방 목록에서, 같은 사람에게 나눔 받더라도 썸네일로 구분할 수 있게 수정하였습니다.
=> 나눔 채팅방 목록에서 썸네일 추가

components/common/shares/Content.tsx, manifest.json, next-pwa.d.ts, next.config.ts, package-lock.json, package.json
- pwa 기본 설정
- manifest.json 설정
- service worker는 next-pwa 라이브러리 사용
- 바텀시트에 white-space 추가
=> 나눔함 바텀시트에 white-space 추가

app/globals.css, app/layout.tsx, app/login/page.tsx, app/users/[publicId]/edit-address/page.tsx, app/users/[publicId]/page.tsx, app/users/components/MyCharacter.tsx, app/users/components/UsersNav.tsx, app/users/components/model/Ground.tsx, app/users/components/model/Nanumi.tsx
Closes #155 
Closes #13
- body 에 overflow-hidden 추가
- 바람개비 애니메이션 추가
- 나누미 애니메이션 수정 - 클릭 시 통통 튀도록
- 높이 값 svh 로 수정
https://github.com/user-attachments/assets/f8d3f670-4bcd-4585-9755-e24950ca09d3
=> 마이페이지 - 나누미 애니메이션 추가

app/group-buy/[groupBuyId]/edit/page.tsx, app/register/group-buy/page.tsx, app/register/share/page.tsx, app/review/[shareId]/new/page.tsx, app/share/[shareId]/edit/page.tsx, components/common/FormImageUpload.tsx, components/common/register/FormMultiImageUpload.tsx, infra/repositories/prisma/share/PrismaShareRepository.ts, lib/constants.ts
- 이미지 업로드 가능 사이즈 5MB로 제한
- 24시간 이내 나눔 등록한 항목 중 완료 가능한 것은 다시 등록 가능하도록 수정
=> 폼 관련 에러 수정

app/components/EndSection.tsx, app/components/MapSection.tsx, app/components/ScrollSection.tsx, app/map/page.tsx, components/lotties/IntroLottie.tsx
Closes #164 
- 메인 페이지 section 별 간격 수정
- 최하단 스크롤 viewport 별 에러 현상 수정
=> 메인페이지 section 별 간격 및 스크롤 에러 수정

app/api/chat/[chatId]/shares/confirm/route.ts, application/usecases/chat/dto/UpdateMeetingDateDto.ts
=> 채팅 관련 dto 수정

infra/repositories/prisma/group-buy/PrismaGroupBuyRepository.ts
Closes #183
- 같이 장보기 기한이 경과 되었으나, 동네 지도 리스트에 출력되는 현상 수정
=> Cluster 기한 경과 시에도 리스트에 보이는 현상
